const EXPRESS_SERVER_PORT = 4000;
const EXPRESS_SERVER_ADDRESS = "http://localhost:"+ EXPRESS_SERVER_PORT + "/graphql";
const MONGO_DB_USER = 'Your-MongoDB-DB-User';
const MONGO_DB_PASS = 'Your-MongoDB-DB-User-Password';
const MONGO_DB_SERVER_NAME = 'Your-Server-Name';
const MONGO_DB_SERVER_ADDRESS = '@Your-MongoDB-URL/' + MONGO_DB_SERVER_NAME;
const MONGO_DB_CREDENTIAL_STRING = "mongodb://" + MONGO_DB_USER + ":" + MONGO_DB_PASS + MONGO_DB_SERVER_ADDRESS

module.exports = {
  MONGO_DB_ADDRESS: MONGO_DB_CREDENTIAL_STRING,
  SERVER_PORT: EXPRESS_SERVER_PORT,
  SERVER_ADDRESS: EXPRESS_SERVER_ADDRESS
};
